name: Run unit tests
on: [push]


jobs:
  tests:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

#    - name: Validate composer.json and composer.lock
#      run: composer validate --strict

    - name: Install dependencies
      run: /usr/bin/php /usr/bin/composer install --prefer-dist --no-progress

    - name: Run test suite
      run: /usr/bin/php /usr/bin/composer run unit
